baseURL = 'https://wpieters.github.io/'
languageCode = 'en-us'
title = 'Wynand Pieters'
theme = 'PaperMod'

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50

[params]
  env = "production"
  title = "Wynand Pieters"
  description = "Personal blog"
  keywords = ["blog", "personal"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  ShowCategories = true
  ShowCategoryInPost = true

[params.profileMode]
  enabled = true
  title = "Wynand Pieters"
  subtitle = "Software Engineering Consultant | DevOps & Architecture | Indie Game Developer"
  imageUrl = "https://avatars.githubusercontent.com/wpieters"
  imageTitle = "Wynand Pieters"
  imageWidth = 160
  imageHeight = 160
  imageLink = "https://github.com/wpieters"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wpieters"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wynand-pieters/"
[[params.socialIcons]]
  name = "dev"
  url = "https://dev.to/wynandpieters"
[[params.socialIcons]]
  name = "itchio"
  url = "https://duhblinnza.itch.io/"
[[params.socialIcons]]
  name = "linktree"
  url = "https://linktr.ee/wynandpieters.dev"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = -90

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = -80

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = -70
